# Generated by Django 3.2.12 on 2022-03-18 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post', 'value')},
        ),
    ]
